### ISSUE TITLE
setup command dont work

### ISSUE THREAD

**Issue by MikeDuxxi** [codeezer/livescore-cli#10]
any help? argument linux is no accepted:

MikeDuxxi@linux:~> git clone https://github.com/codeezer/livescore-cli.git
Cloning into 'livescore-cli'...
remote: Counting objects: 975, done.
remote: Total 975 (delta 0), reused 0 (delta 0), pack-reused 975
Receiving objects: 100% (975/975), 1.39 MiB | 671.00 KiB/s, done.
Resolving deltas: 100% (598/598), done.
MikeDuxxi@linux:~> cd livescore-cli
MikeDuxxi@linux:~/livescore-cli> ./setup (linux)
bash: syntax error near unexpected token `linux'
MikeDuxxi@linux:~/livescore-cli> ll
total 24
drwxr-xr-x 2 MikeDuxxi users  156 Feb  4 17:28 lib
-rwxr-xr-x 1 MikeDuxxi users 1711 Feb  4 17:28 livescore.py
-rwxr-xr-x 1 MikeDuxxi users 6963 Feb  4 17:28 logo.png
-rwxr-xr-x 1 MikeDuxxi users  515 Feb  4 17:28 mac_setup
-rwxr-xr-x 1 MikeDuxxi users 2195 Feb  4 17:28 README.md
-rwxr-xr-x 1 MikeDuxxi users  176 Feb  4 17:28 setup
MikeDuxxi@linux:~/livescore-cli> ./setup 
./setup: line 7: pip2: command not found

**Comment by nabinkhadka** [comment]
@MikeDuxxi Your system does not seem to have pip installed. What does the command "which pip2" output? 
Also you can edit the last line of the setup file and write "pip" instead of "pip2". Then retry executing the command.

**Comment by MikeDuxxi** [comment]
i will try later at home. thanks

**Comment by codeezer** [comment]
Hello Mike,

Did you manage to get it working on your system?

**Comment by MikeDuxxi** [comment]
@nabinkhadka you are right I have python but I didn't have PIP installed, so I install pythonsetuptools first and didn't install pip yet, so the end I try sudo apt-get install python-pip python-dev build-essential
and pip was installed and now it works. 👍 

@codeezer  now yes with the help of nabnkhadka , see my answer to him.

thank you both :)
