### ISSUE TITLE
Error in Score table

### ISSUE THREAD

**Issue by AndreaDiPietro92** [codeezer/livescore-cli#13]
Command:  ```python3 ./livescore.py -s seriea  ```

Error :
Get the SCORES + this error
 ``` 
Traceback (most recent call last):
  File "./livescore.py", line 58, in <module>
    main()
  File "./livescore.py", line 35, in main
    lsprint.scores(lsweb.get_score(URL[k][1]), k)
  File "/home/user/livescore-cli/lib/lsprint.py", line 54, in scores
    away_team = each_row[3].strip()
IndexError: list index out of range
```

**Comment by codeezer** [comment]
Awesome. Fixed the issue. pull the latest code and let me know if that
works or not. :)

**Comment by AndreaDiPietro92** [comment]
Thank you :-) Now the client works! 
The scores is now displayed correctly but, to stop them, is necessary press <Ctrl-C>. It's normal?

**Comment by codeezer** [comment]
Yes, that is normal. It was originally designed to refresh the score every 5-7 seconds, automatically.

**Comment by AndreaDiPietro92** [comment]
Then everything works. Thank you
