### ISSUE TITLE
Traceback when trying to run livescore

### ISSUE THREAD

**Issue by johnpiers** [codeezer/livescore-cli#14]
I'm not really a boffin when it comes to this sort of thing, somebody could please help me out?

`... Fetching information from www.livescore.com ... 
Displaying Table for Barclay's Premier League
Traceback (most recent call last):
  File "/usr/local/bin/livescore", line 66, in <module>
    main()
  File "/usr/local/bin/livescore", line 32, in main
    lsprint.table(lsweb.get_table(URL[k][1]), k)
  File "/opt/livescore-cli/lib/lsweb.py", line 66, in get_table
    content = get_content_ts(url)
  File "/opt/livescore-cli/lib/lsweb.py", line 45, in get_content_ts
    [content] = soup.select('body > div.wrapper > div.content')
ValueError: not enough values to unpack (expected 1, got 0)`

**Comment by kiya1990** [comment]
I also got this error

 ... Fetching information from www.livescore.com ... 
Displaying Table for Barclay's Premier League
Traceback (most recent call last):
  File "/usr/local/bin/livescore", line 66, in <module>
    main()
  File "/usr/local/bin/livescore", line 32, in main
    lsprint.table(lsweb.get_table(URL[k][1]), k)
  File "/opt/livescore-cli/lib/lsweb.py", line 66, in get_table
    content = get_content_ts(url)
  File "/opt/livescore-cli/lib/lsweb.py", line 45, in get_content_ts
    [content] = soup.select('body > div.wrapper > div.content')
ValueError: not enough values to unpack (expected 1, got 0)



anyone could help how to resolve it?

**Comment by johnpiers** [comment]
Yup, I've never got this to work, the only command that doesn't give an error is : livescore --help  :-) So that's not really "helping me much! It looks very quiet around here so not really sure if we're going to get any help. i'm not really very good with python tried to search around for advice but haven't found any yet. :-(

**Comment by codeezer** [comment]
Hey all, I acknowledge the issue. It is because the source we relied on is no longer working. I am looking for an API or a simple website that provides the score in real time. If you guys wanna contribute, let me know.

**Comment by codeezer** [comment]
This issue is fixed on the new commit. Pull the latest code and it should work.

**Comment by johnpiers** [comment]
Thanks man. I also got sidetracked since I last communicated with you.
Thanks so much. When I get back to my office I'll give it a whirl.
Regards.

**Comment by codeezer** [comment]
My pleasure, John. It's just I have been busy these years, so, couldn't
find time and courage to fix the issue, and also the livescore is
continuously changing its website layout.
It works, for now, I am planning to write much more robust code now, let's
see.

**Comment by johnpiers** [comment]
A quick last chirp [hopefully for a while :-) ]. Deleted all and any folders called "livescore" then ran 'git clone https://github.com/codeezer/livescore-cli.git' then 'cd livescore-cli' and lastly the ./setup and voilà, everything working like a charm.

Thanks  again Ramesh

**Comment by johnpiers** [comment]
Hi everyone. Got the traceback problem again. 
```
Traceback (most recent call last):
  File "/usr/local/bin/livescore", line 60, in <module>
    main()
  File "/usr/local/bin/livescore", line 33, in main
    lsprint.table(lsweb.get_table(URL[k][1]), k)
  File "/opt/livescore-cli/lib/lsprint.py", line 129, in table
    team_name = each_row[1]
IndexError: string index out of range
```
