### ISSUE TITLE
Bundesliga Table (numbers mixed up)

### ISSUE THREAD

**Issue by platschi** [codeezer/livescore-cli#4]
Hi! Love the livescore-cli! Thanks for the work! Just an issue to report; Some German clubs end with numbers (Schalke 04, Mainz 05, Hannover 96). The script interprets these numbers as GP, which then mixes up their league table data. Well, see screenshot :)

![table](https://cloud.githubusercontent.com/assets/548702/13029405/30e2bf86-d26a-11e5-95ca-fe5a944f544e.png)

**Comment by anujgtm1** [comment]
Hi platschi!
Thank you for your valuable feedback. The issue of "club names including numbers" that  you have raised has been solved. Please check with any other issue regarding this problem.
And thank you for supporting this application. Furthermore, please report any other issues you encounter with the application.
Regards,
Anuj
