### ISSUE TITLE
quite incorrect time

### ISSUE THREAD

**Issue by codeezer** [codeezer/livescore-cli#9]
![image](http://i.imgur.com/WcO6F7t.jpg)

Crystal Palace vs Everton will start at 12:45 NST but it's showing 1:00 NST

**Comment by anujgtm1** [comment]
Will take some time. The entire date-time systems seems to need a change.

**Comment by codeezer** [comment]
I found out that the date was incorrect because of int and float conversion.
The problem is now solved.
